imports:
  - { resource: parameters.yml }
  - { resource: "@AppBundle/Resources/config/services.yml" }

framework:
  # Framework Bundle
  secret: "%kernel.secret%"

  # Templating Service
  templating:
    engines: ['twig']

# Twig Bundle
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"