imports:
  - { resource: parameters.yml }
  - { resource: "@AppBundle/Resources/config/services.yml" }

framework:
  # Required configuration
  secret: "%kernel.secret%"
  assets: ~
  form: ~
  templating:
    engines: ['twig']

  # Translator service
  translator: { fallbacks: ["%locale%"] }
  default_locale: "%locale%"

  # Validation service
  validation: { enable_annotations: true }

  # Http Cache service
  esi: ~
  fragments: ~
  trusted_proxies: [127.0.0.1, "::1"]
  http_method_override: true
