imports:
  - { resource: parameters.yml }
  - { resource: "@VendorNameProjectNameBundle/Resources/config/services.yml" }

framework:
  # Required configuration
  secret: "%kernel.secret%"
  assets: ~
  form: ~
  templating:
    engines: ['twig']

  # Translator service
  translator: { fallbacks: ["%locale%"] }
  default_locale: "%locale%"

  # Validation service
  validation: { enable_annotations: true }